### Get all areas
GET http://localhost:3000/api/areas


### Get area by ID
GET http://localhost:3000/api/areas/6462a6f04c3d0ddd28897fb4


### Get non-existing area
GET http://localhost:3000/api/areas/not-existing-id